apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-pipeline-test
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: 663151261323.dkr.ecr.eu-central-1.amazonaws.com/test-pipeline-chart
    targetRevision: 2023-07-22-20-01-ed503518a82fead670afa5c7a652a64e22941f2a
    helm:
      releaseName: helm-chart-test-release
  destination:
    server: "https://kubernetes.default.svc"
    namespace: playground
